spring:
  application:
    name: my-project-backend
  security:
    jwt:
      key: abcdefghijk
      expire: 7

  datasource:
    username: root
    password: 20010608
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test

